const uint8_t positionIconBluetooth[2] =    {110, 10};              // x, y
const uint8_t positionLabelBrightness[2] =  {3, 27};                // x, y
const uint8_t positionLabelRed[2] =         {3, 38};                // x, y
const uint8_t positionLabelGreen[2] =       {3, 49};                // x, y
const uint8_t positionLabelBlue[2] =        {3, 60};                // x, y
const uint8_t positionValueRed[2] =         {50, 27};               // x, y
const uint8_t positionValueGreen[2] =       {50, 38};               // x, y
const uint8_t positionValueBlue[2] =        {50, 49};               // x, y
const uint8_t positionFrameRed[2] =         {40, 19};               // x, y
const uint8_t positionFrameGreen[2] =       {40, 30};               // x, y
const uint8_t positionFrameBlue[2] =        {40, 41};               // x, y
const uint8_t sizeFrameValues[2] =          {85, 9};                // width, height
const uint8_t colorValues =                 1;
const uint8_t lineSeparator[3] =            {0, 13, 128};       // x, y, length
const String labelValues[4] =               {"BRGT", "RED", "GREEN", "BLUE"};